import { useState } from 'react';

export default function ExecutiveReportModal({ project, risks = [], onClose }) {
  const [copied, setCopied] = useState(false);

  const reportDate = new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric'
  });

  const criticalRisks = risks.filter((r) => r.severity === 'Critical');
  const highRisks = risks.filter((r) => r.severity === 'High');
  const mediumRisks = risks.filter((r) => r.severity === 'Medium');
  const lowRisks = risks.filter((r) => r.severity === 'Low');

  const reportMarkdown = `
# 🛡️ EXECUTIVE RISK ASSESSMENT REPORT
**Project Name**: ${project?.name || 'Project'}  
**Date**: ${reportDate}  
**Overall Risk Score**: ${project?.overall_risk_score ?? 'N/A'} / 10  
**Audit Classification**: ${project?.overall_risk_score >= 7 ? 'ELEVATED RISK POSTURE' : 'STABLE RISK POSTURE'}

---

## 📊 1. EXECUTIVE SUMMARY
An automated AI security and compliance risk analysis was conducted for **${project?.name}**.
- Total Risks Identified: **${risks.length}**
- Critical Vulnerabilities: **${criticalRisks.length}**
- High Priority Risks: **${highRisks.length}**
- Medium Priority Risks: **${mediumRisks.length}**
- Low Priority Risks: **${lowRisks.length}**

---

## 🎯 2. DETAILED THREAT BREAKDOWN

${risks.map((r, idx) => `
### ${idx + 1}. [${r.severity.toUpperCase()}] ${r.title}
- **Category**: ${r.category}
- **Risk Score**: ${r.risk_score} / 10
- **Probability**: ${r.probability} | **Impact**: ${r.impact}
- **Explanation**: ${r.explanation}
- **Mitigation Roadmap**:
${r.mitigation ? r.mitigation.map((m) => `  - [ ] ${m}`).join('\n') : '  - [ ] Action pending'}
`).join('\n')}

---
*Generated by AI Risk Manager — Continuous Cybersecurity Intelligence Platform*
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const printReport = () => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html>
        <head>
          <title>Executive Risk Audit Report - ${project?.name}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            h1 { color: #0f172a; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
            .badge { display: inline-block; padding: 4px 10px; border-radius: 4px; font-weight: bold; }
            .critical { background: #fee2e2; color: #991b1b; }
            .high { background: #ffedd5; color: #9a3412; }
            .card { border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; margin-bottom: 16px; }
          </style>
        </head>
        <body>
          <h1>🛡️ Executive Security Audit Report</h1>
          <p><strong>Project:</strong> ${project?.name}</p>
          <p><strong>Overall Risk Score:</strong> ${project?.overall_risk_score ?? 'N/A'} / 10</p>
          <hr />
          <h3>Identified Risks</h3>
          ${risks.map(r => `
            <div class="card">
              <h4>[${r.severity}] ${r.title} (${r.risk_score}/10)</h4>
              <p><strong>Category:</strong> ${r.category}</p>
              <p>${r.explanation}</p>
              <h5>Mitigation Actions:</h5>
              <ul>${(r.mitigation || []).map(m => `<li>${m}</li>`).join('')}</ul>
            </div>
          `).join('')}
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: '800px' }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div>
            <span style={{ fontSize: '0.78rem', fontWeight: 800, color: 'var(--accent-primary)', letterSpacing: '0.08em' }}>
              OFFICIAL AUDIT REPORT
            </span>
            <h2 style={{ fontSize: '1.4rem', color: 'var(--text-primary)', margin: 0 }}>
              📄 Executive Risk Assessment Document
            </h2>
          </div>
          <button className="btn btn-ghost btn-sm" onClick={onClose}>✕</button>
        </div>

        <div style={{ background: 'var(--bg-input)', padding: '16px', borderRadius: '12px', marginBottom: '20px', fontSize: '0.85rem', fontFamily: 'var(--font-mono)', maxHeight: '350px', overflowY: 'auto', border: '1px solid var(--border-subtle)' }}>
          <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: 'var(--text-secondary)' }}>
            {reportMarkdown}
          </pre>
        </div>

        <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end', flexWrap: 'wrap' }}>
          <button className="btn btn-secondary" onClick={copyToClipboard}>
            {copied ? '✓ Copied to Clipboard!' : '📋 Copy Markdown Report'}
          </button>
          <button className="btn btn-primary" onClick={printReport}>
            🖨️ Print / Save as PDF
          </button>
        </div>

      </div>
    </div>
  );
}
